-Wno-EOFNEWLINE
-Wno-WIDTHCONCAT
-Wno-DECLFILENAME
-Wno-UNUSEDSIGNAL
-Wno-UNUSEDPARAM
-Wno-PINCONNECTEMPTY
-Wno-LATCH
-Wno-UNOPTFLAT
-Wno-CASEINCOMPLETE
-Wno-INITIALDLY
-Wno-WIDTH
-Wno-CASEOVERLAP
-Wno-SELRANGE
-Wno-VARHIDDEN
-I../basejump_stl/bsg_misc
-I../v/gbp_pe

../basejump_stl/bsg_misc/bsg_defines.sv
../v/bsg_manycore_pkg.sv
../v/gbp_pe/gbp_pkg.sv
../v/gbp_pe/scoreboard_prefetcher.sv
../v/gbp_pe/pull_client.sv
../v/gbp_pe/response_collector.sv
../v/gbp_pe/gbp_pe_fetch_subsystem.sv
