-Wno-EOFNEWLINE
-Wno-WIDTHCONCAT
-Wno-DECLFILENAME
-Wno-UNUSEDSIGNAL
-Wno-UNUSEDPARAM
-Wno-PINCONNECTEMPTY
-Wno-LATCH
-Wno-UNOPTFLAT
-Wno-CASEINCOMPLETE
-Wno-INITIALDLY
-Wno-WIDTH
-Wno-CASEOVERLAP
-Wno-SELRANGE
-Wno-VARHIDDEN
-I../basejump_stl/bsg_misc
-I../v/gbp_pe

../basejump_stl/bsg_misc/bsg_defines.sv
../v/bsg_manycore_pkg.sv
../v/gbp_pe/gbp_pkg.sv
../v/gbp_pe/phase_controller.sv
../v/gbp_pe/node_scheduler.sv
../v/gbp_pe/metadata_scanner.sv
../v/gbp_pe/gbp_pe_control_subsystem.sv
tops/unit/gbp_pe_control_subsystem_top.sv
