// Interface definitions
// Generated by HDoc

// status interface for each transaction between compute unit and scratchpad memory
interface transaction_read_if;

  // Inputs (to/from the interface)
  logic valid;
  logic [31:0] addr;
  logic busy;

  // Outputs (from the interface)
  logic ready;
  logic [31:0] rdata;

  // Modports
  modport master(input valid, addr, busy, output ready, rdata);

  modport slave(output valid, addr, busy, input ready, rdata);

endinterface

// read data channel: read_stream_engine -> compute path
interface read_stream_if;

  // Inputs (to/from the interface)
  logic valid;
  logic [31:0] data;

  // Outputs (from the interface)
  logic ready;

  // Modports
  modport master(input valid, data, output ready);

  modport slave(output valid, data, input ready);

endinterface

// write data channel: compute path -> write_stream_engine
interface write_stream_if;

  // Inputs (to/from the interface)
  logic valid;
  logic [31:0] data;

  // Outputs (from the interface)
  logic ready;

  // Modports
  modport master(input valid, data, output ready);

  modport slave(output valid, data, input ready);

endinterface

// interface between scratchpad and streaming engine
interface scratchpad_if;

  // Inputs (to/from the interface)
  logic valid;
  logic [31:0] addr;
  logic wen;

  // Outputs (from the interface)
  logic ready;

  // Modports
  modport master(input valid, addr, wen, output ready);

  modport slave(output valid, addr, wen, input ready);

endinterface

// interface between PE top module and the NoC
interface endpoint_if;

  // Inputs (to/from the interface)
  logic valid_i;
  logic ready_i;
  logic [BEAT_BITS:0] data_i;

  // Outputs (from the interface)
  logic valid_o;
  logic ready_o;
  logic [BEAT_BITS:0] data_o;

  // Modports
  modport master(input valid_i, ready_i, data_i, output valid_o, ready_o, data_o);

  modport slave(output valid_i, ready_i, data_i, input valid_o, ready_o, data_o);

endinterface

// interface between control unit and stream dispatcher
interface control_dispatch_if;
  import gbp_pkg::*;
  // Inputs (to/from the interface)
  logic                    ready;

  // Outputs (from the interface)
  logic                    valid;
  // Stream mode: STREAM_META=metadata, STREAM_VEC=vector, STREAM_MESSAGE=message
  stream_type_e            mode;
  // Node address in scratchpad memory (byte address, SPM_ADDR_W bits)
  logic [  SPM_ADDR_W-1:0] node_address;
  // Transfer size in bytes (1 to 2^XFER_BYTES_W bytes)
  logic [XFER_BYTES_W-1:0] xfer_bytes;  // XFER_BYTES_W
  // Stride between consecutive beats in bytes
  logic [STEP_BYTES_W-1:0] addr_step_bytes;  // STEP_BYTES_W
  // stream_type_e stream_type;

  // Modports
  modport master(input ready, output valid, mode, node_address, xfer_bytes, addr_step_bytes);

  modport slave(output ready, input valid, mode, node_address, xfer_bytes, addr_step_bytes);

endinterface

// interface between control unit and compute unit
interface control_compute_if;
  import gbp_pkg::*;

  // Inputs (to/from the interface)
  // Operation complete signal (asserted when compute finishes)
  logic done;
  // Command ready: consumer is ready to accept command
  logic cmd_ready;
  // Response done: transaction completion signal
  logic rsp_done;

  // Outputs (from the interface)
  // Start signal to compute unit
  logic start;
  // Mode: 0=read stream, 1=write stream
  logic mode;
  // Command valid: command is ready for consumption (cmd_valid && cmd_ready = accepted)
  logic cmd_valid;
  // Command kind: 0=read, 1=write
  logic cmd_kind;
  // Target node index in PE array (NODE_ID_W bits)
  logic [NODE_ID_W-1:0] cmd_node_idx;
  // First iteration indicator (1 for iteration 0, 0 otherwise)
  logic cmd_iter0;
  // Transaction ID for matching responses (TXN_ID_W bits)
  logic [TXN_ID_W-1:0] cmd_txn_id;

  // Modports
  modport master(
      input done,
      input cmd_ready,
      input rsp_done,
      output start,
      output mode,
      output cmd_valid,
      output cmd_kind,
      output cmd_node_idx,
      output cmd_iter0,
      output cmd_txn_id
  );

  modport slave(
      output done,
      output cmd_ready,
      output rsp_done,
      input start,
      input mode,
      input cmd_valid,
      input cmd_kind,
      input cmd_node_idx,
      input cmd_iter0,
      input cmd_txn_id
  );

endinterface

// interface between streaming engine and control unit
interface stream_control_if;
  import gbp_pkg::*;

  // Outputs (from the interface)
  logic [7:0] occ;
  logic afull;
  logic meta_valid;
  logic [BEAT_BITS-1:0] meta_data;

  // Modports
  modport master(output occ, afull, meta_valid, meta_data);

  modport slave(input occ, afull, meta_valid, meta_data);

endinterface

interface stream_dispatcher_if;

  // Inputs (to/from the interface)
  logic ready;

  // Outputs (from the interface)
  logic valid;
  gbp_pkg::desc_t data;

  // Modports
  modport master(input ready, output valid, data);

  modport slave(output ready, input valid, data);

endinterface

interface mic_spm_arbiter_if;
  import gbp_pkg::*;

  logic spm_rd_req_valid;
  logic [SPM_ADDR_W-1:0] spm_rd_req_addr;
  logic [XFER_BYTES_W-1:0] spm_rd_req_bytes;

  logic spm_rd_rsp_valid;
  logic [BEAT_BITS-1:0] spm_rd_rsp_data;

  modport master(
      output spm_rd_req_valid,
      output spm_rd_req_addr,
      output spm_rd_req_bytes,
      input spm_rd_rsp_data,
      input spm_rd_rsp_valid
  );

  modport slave(
      input spm_rd_req_valid,
      input spm_rd_req_addr,
      input spm_rd_req_bytes,
      output spm_rd_rsp_data,
      output spm_rd_rsp_valid
  );
endinterface

interface mic_spm_arbiter_wr_if;
  import gbp_pkg::*;

  logic                  spm_wr_req_valid;
  logic [SPM_ADDR_W-1:0] spm_wr_req_addr;
  logic [ BEAT_BITS-1:0] spm_wr_req_data;
  logic [   WSTRB_W-1:0] spm_wr_req_wstrb;
  logic                  spm_wr_req_ready;

  modport master(
      output spm_wr_req_valid,
      output spm_wr_req_addr,
      output spm_wr_req_data,
      output spm_wr_req_wstrb,
      input spm_wr_req_ready
  );

  modport slave(
      input spm_wr_req_valid,
      input spm_wr_req_addr,
      input spm_wr_req_data,
      input spm_wr_req_wstrb,
      output spm_wr_req_ready
  );
endinterface

interface spm_bank_if;
  import gbp_pkg::*;

  logic                  bank_rd_en;
  logic [ BANK_ID_W-1:0] bank_rd_bank;
  logic [ROW_ADDR_W-1:0] bank_rd_addr;
  logic [ BEAT_BITS-1:0] bank_rd_data;

  logic                  bank_wr_en;
  logic [ BANK_ID_W-1:0] bank_wr_bank;
  logic [ROW_ADDR_W-1:0] bank_wr_addr;
  logic [ BEAT_BITS-1:0] bank_wr_data;
  logic [   WSTRB_W-1:0] bank_wr_wstrb;

  modport master(
      output bank_rd_en,
      output bank_rd_bank,
      output bank_rd_addr,
      input bank_rd_data,
      output bank_wr_en,
      output bank_wr_bank,
      output bank_wr_addr,
      output bank_wr_data,
      output bank_wr_wstrb
  );

  modport slave(
      input bank_rd_en,
      input bank_rd_bank,
      input bank_rd_addr,
      output bank_rd_data,
      input bank_wr_en,
      input bank_wr_bank,
      input bank_wr_addr,
      input bank_wr_data,
      input bank_wr_wstrb
  );
endinterface
