// mic_read
// memory interface controller (read)
// Generated by HDoc

import gbp_pkg::*;
module mic_read
(
    input logic clk_i,
    input logic reset_i,
    // with addr fifo
    input logic valid_i,
    input logic [SPM_ADDR_W-1:0] data_i,
    output logic unqueue_o,
    // with spm arbiter
    mic_spm_arbiter_if.master mic_to_spm_arbiter,
    // with data_fifo
    input logic ready_i,
    output logic valid_o,
    output logic [BEAT_BITS-1:0] data_o,
    output logic busy_o
);

  // ============================================================
  // FSM states
  // ============================================================
  typedef enum logic [1:0] {
    IDLE       = 2'b00,
    REQ_SEND   = 2'b01,
    WAIT_RSP   = 2'b10,
    WRITE_FIFO = 2'b11
  } state_e;

  state_e state_r, state_n;

  // ============================================================
  // Internal signals
  // ============================================================
  logic [SPM_ADDR_W-1:0] addr_r;
  logic [ BEAT_BITS-1:0] rsp_data_r;
  logic                  accept_addr_lo;

  // SPM request can be sent when:
  // - addr_fifo has valid data
  // - SPM arbiter is ready
  assign accept_addr_lo = (state_r == IDLE) & valid_i;
  assign mic_to_spm_arbiter.spm_rd_req_valid = accept_addr_lo;
  // 接收新地址的同拍直接使用队头值，之后一律使用锁存值。
  assign mic_to_spm_arbiter.spm_rd_req_addr = accept_addr_lo ? data_i[SPM_ADDR_W-1:0] : addr_r;
  // Full-beat request width is part of gbp_pkg ingress/SPM contract.
  assign mic_to_spm_arbiter.spm_rd_req_bytes = SPM_RD_REQ_BYTES_FULL_BEAT;

  // 只有在真正接收一条新地址进入本模块时才推进 addr_fifo。
  assign unqueue_o = accept_addr_lo;

  // Write to data_fifo
  assign valid_o = (state_r == WRITE_FIFO);
  assign data_o = rsp_data_r;
  assign busy_o = (state_r != IDLE);

  // ============================================================
  // FSM sequential logic
  // ============================================================
  always_ff @(posedge clk_i) begin
    if (reset_i) begin
      state_r    <= IDLE;
      addr_r     <= '0;
      rsp_data_r <= '0;
    end else begin
      state_r <= state_n;

      // Latch address when accepting from addr_fifo
      if (accept_addr_lo) begin
        addr_r <= data_i[SPM_ADDR_W-1:0];
      end

      // Latch response data when it arrives
      if (mic_to_spm_arbiter.spm_rd_rsp_valid) begin
        rsp_data_r <= mic_to_spm_arbiter.spm_rd_rsp_data;
      end
    end
  end

  // ============================================================
  // FSM next-state logic
  // ============================================================
  always_comb begin
    state_n = state_r;

    case (state_r)
      IDLE: begin
        if (accept_addr_lo) begin
          state_n = REQ_SEND;
          $display("MIC_READ_REQ %m addr=%h", data_i);
        end
      end

      REQ_SEND: begin
        // Request sent, wait for response
        state_n = WAIT_RSP;
      end

      WAIT_RSP: begin
        if (mic_to_spm_arbiter.spm_rd_rsp_valid) begin
          state_n = WRITE_FIFO;
          $display("MIC_READ_RSP %m addr=%h data=%h", addr_r, mic_to_spm_arbiter.spm_rd_rsp_data);
        end
      end

      WRITE_FIFO: begin
        // Write to data_fifo, wait for it to accept
        if (ready_i) begin
          state_n = IDLE;
        end
      end

      default: state_n = IDLE;
    endcase
  end

endmodule
