// stream_dispatcher
// Generated by HDoc

import gbp_pkg::*;
module stream_dispatcher
(
    input logic clk_i,
    input logic reset_i,
    control_dispatch_if.slave control_dispatch_if,
    stream_dispatcher_if.master stream_dispatcher_if_read,
    stream_dispatcher_if.master stream_dispatcher_if_write
);

  // Invalid mode: 2'b11 (mode=3) is outside valid classes META(0)/VEC(1)/MESSAGE(2)
  // Policy: no descriptor issued, dispatcher remains non-blocking to avoid deadlock
  logic is_valid_mode;
  assign is_valid_mode = (control_dispatch_if.mode != 2'b11);

  desc_t desc_lo;
  always_comb begin : control_analysis
    desc_lo = '0;
    desc_lo.op = OP_READ;
    desc_lo.base_addr = control_dispatch_if.node_address;
    desc_lo.xfer_bytes = control_dispatch_if.xfer_bytes;
    desc_lo.addr_step_bytes = control_dispatch_if.addr_step_bytes;
    desc_lo.txn_id = '0;
    desc_lo.operand_id = {2'b00, control_dispatch_if.mode};
    desc_lo.wstrb_mode = WSTRB_FULL;
    desc_lo.dim = 1'b0;
    desc_lo.y_count = '0;
    desc_lo.y_stride_bytes = '0;
    desc_lo.addr_src = 1'b0;

    // Only issue descriptor for valid modes
    stream_dispatcher_if_read.valid = is_valid_mode ? control_dispatch_if.valid : 1'b0;
    stream_dispatcher_if_read.data = desc_lo;

    stream_dispatcher_if_write.valid = 1'b0;
    stream_dispatcher_if_write.data = '0;

    // For invalid mode, always ready (non-blocking); otherwise follow read channel
    control_dispatch_if.ready = is_valid_mode ? stream_dispatcher_if_read.ready : 1'b1;
    
  end

endmodule
