-Wno-EOFNEWLINE
-Wno-WIDTHCONCAT
-Wno-DECLFILENAME
-Wno-UNUSEDSIGNAL
-Wno-UNUSEDPARAM
-Wno-PINCONNECTEMPTY
-Wno-LATCH
-Wno-UNOPTFLAT
-Wno-CASEINCOMPLETE
-Wno-INITIALDLY
-Wno-WIDTH
-Wno-CASEOVERLAP
-Wno-SELRANGE
-Wno-VARHIDDEN
-I../basejump_stl/bsg_misc
-I../basejump_stl/bsg_fpu
-I../v/gbp_pe/compute/include
-I../imports/HardFloat/source
-I../imports/HardFloat/source/RISCV

../basejump_stl/bsg_misc/bsg_defines.sv
../v/bsg_manycore_pkg.sv
../v/gbp_pe/gbp_pkg.sv
../v/gbp_pe/phase_controller.sv
../v/gbp_pe/node_scheduler.sv
../v/gbp_pe/metadata_scanner.sv
../v/gbp_pe/gbp_pe_control_subsystem.sv

../basejump_stl/bsg_misc/bsg_less_than.sv
../basejump_stl/bsg_misc/bsg_reduce.sv
../basejump_stl/bsg_misc/bsg_mul_synth.sv
../basejump_stl/bsg_misc/bsg_priority_encode.sv
../basejump_stl/bsg_misc/bsg_priority_encode_one_hot_out.sv
../basejump_stl/bsg_misc/bsg_encode_one_hot.sv
